#定义不同的阶段，按实际增减
stages:
#  - build
#  - test
  - deploy
  - rollback

#定义before_script：在每个job被执行之前都会先调用执行（可选）
#before_script:
#  - global before script

更新EAP测试环境:
  stage: deploy
  script:
    - bash /home/gitlab-runner/exclusiveCloudTesting/exclusiveCloudChild/runner.sh commit_testing
  tags:
    - exclusiveCloudChild
  only:
    - feature/1.0.0
  when: "manual"
